CC	 	= aarch64-linux-gnu 
CFLAGS  ?= -Wall -Wno-multichar -Wno-unused-but-set-variable -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -pthread -lssl -lcrypto -ldl -lm -lrt -lstdc++ -L. 

OBJ			= bin/armhf
EXECUTABLE 	= bin/raop_play-armhf

include Makefile

